// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddgslseiakhruzevrszw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkZ3Nsc2VpYWtocnV6ZXZyc3p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMjc1MjMsImV4cCI6MjA2NjcwMzUyM30.-93iX4ehvxZYGGRp2By2C3BAjiiFrBIkov5Pla0ADxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);